name = "exam-tracker"
main = "src/index.js"
compatibility_date = "2025-11-08"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[kv_namespaces]]
binding = "EXAM_DATA"
id = "6b5f68231bbd4613a4900e10219cf7d3"

[vars]
ADMIN_PASSWORD = "changeme123"
